# This workflow will launch at 00:00 every day
name: RDF Tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rdf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: echo "potato" > potato.md
      - name: configure git
        run: |
          git config user.name 'pepegar'
          git config user.email 'pepegar@users.noreply.github.com'
      - name: Create Pull Request
        if: env.NO_CHANGES == null
        id: cpr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-rdf-report
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          assignees: pepegar
          reviewers: pepegar
      - name: Show Pull Request URL
        if: env.PULL_REQUEST_NUMBER != null
        run: 'echo "Pull-request created: https://github.com/gsk-aiops/bellman/pull/${{ env.PULL_REQUEST_NUMBER }}"'
